name: Daily Report
on:
  schedule:
    - cron: '0 6 * * *'  # 08:00 за Києвом
  workflow_dispatch:      # Кнопка для ручного запуску

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/set-python@v4
        with:
          python-version: '3.10'
      - name: Install requests
        run: pip install requests
      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
        run: python main.py
