name: Daily Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
        run: python main.py
