name: Daily Channel Content

on:
  schedule:
    # Час вказано по UTC (Київ -2 години взимку)
    - cron: '0 6 * * *'  # 08:00 за Києвом (Ранок)
    - cron: '0 9 * * *'  # 11:00 за Києвом (Цитата)
    - cron: '0 12 * * *' # 14:00 за Києвом (Лайфхак)
    - cron: '0 18 * * *' # 20:00 за Києвом (Вечір)
  workflow_dispatch:      # Кнопка для ручного тесту

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run logic
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
